### ISSUE TITLE
invalid file structure when uploading a csv

### ISSUE THREAD

**Issue by jschmidt12** [OpenTreeMap/OTM2#2006] opened 2015-05-15 15:48 UTC
When trying to upload a csv that has been saved on a mac the user gets these two messages:

“invalid file structure” and “new-line character seen in unquoted field-do you need to open the file in universal-newline mode?”

**Comment by RickMohr** [comment] 2015-05-15 16:06
We should fix this soon because users keep hitting it.

**Comment by jwalgran** [comment] 2015-05-19 21:40
Duplicate of #1998

**Closed by jwalgran** 2015-05-19 21:40 UTC
Labels: bug, duplicate, unverified
