### ISSUE TITLE
Importer: File structure error is unclear

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1898] opened 2015-01-13 19:14 UTC
I tried to upload an excel file instead of a CSV. The error message I got was:

There were errors in the file structure: An exception was raised while uploading the file: line contains NULL byte

Anyway this could be adjust to say: Incorrect file type. Please upload a CSV

**Comment by steventlamb** [comment] 2015-01-14 17:16
This is not as simple as it might seem.

Right now, we're not set up to have internal and external error metadata, so essentially if we delete that message from presentation, we'd have to stop it from ever being stored in the database, which would be a little bit of a loss for developer debugging. Also, @RickMohr suggested that this particular level of detail could be useful for end users if they upload a CSV that causes an exception, which I agree with. The problem is that invalid CSVs will get useful information, but csv-like non-csv files, like excel files, will get strange messages, as was raised by this bug report.

Some of this could be fixed by discussing and allotting more time, but the problem of discovering the filetype of the uploaded file is still not an easy one.

A quick, easy suggestion raised by @maurizi and supported by @RickMohr and myself is to limit the types uploadable files in the file upload dialog provided by the browser. This way, the only exception-raising files that could make it to the server are invalid CSVs, which may result in useful error output. 

This works nicely, except that it is not well supported by all browsers. It won't work in firefox until April, but appears to work on Chrome (confirmed), IE 10+ (awaiting confirmation) and Opera.

Thoughts?

**Comment by dboyer** [comment] 2015-01-14 17:41
I like the idea of limiting the types of uploadable files but don't love the idea that it won't work well in Firefox. Rather than spending time changing the error message, my vote is to wait until April and then implement the file type limit.

**Comment by jwalgran** [comment] 2015-01-14 17:41
Limiting extensions in the file browser is a good, general feature, especially if it gracefully degrades to a noop if the browser does not support it.

To help our browser coverage, we could also add some client side validation to check the last four characters of the file field value and, if they are not ".csv," disable the "Import" button, and show a message.

This seems like a reasonable short term fix.

**Comment by maurizi** [comment] 2015-01-14 17:43
@dboyer This will degrade nicely in Firefox right now.  The bug that will be fixed in April is that it shows "CSV files" when you use this `accept` attribute in the filetype dropdown, but it does not default to "CSV files".  I don't think we should wait until April to do this, I think we should do it now.

**Comment by dboyer** [comment] 2015-01-14 17:51
Fine by me then. Let's make the fix.

**Comment by jwalgran** [comment] 2015-01-14 17:58
We can provide a little more guidance by changing the message next to the file field, too:

![screen shot 2015-01-14 at 10 57 21 am](https://cloud.githubusercontent.com/assets/17363/5744252/3f28bff2-9bdc-11e4-9d15-ac14c450dbe2.png)

**Comment by steventlamb** [comment] 2015-01-14 18:33
Cool, I'll do both.

**Closed** 2015-01-14 19:42 UTC
Labels: unverified
