### ISSUE TITLE
Management page on dormant instance is accessible by non map owners

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/OTM2#2007] opened 2015-05-18 14:15 UTC
I logged in to a dormant instance as a regular admin with management rights and the "Manage" link didn't appear for me. However, I was still able to access the management page and make changes by entering the URL directly. 

Unrelated, but the error message told me to login when I was already logged in.

In this screenshot I'm logged in as "administrator" on the left, and "kdeloach" on the right.

![image](https://cloud.githubusercontent.com/assets/43062/7733236/d1e8efc4-fefb-11e4-901a-d9f39a71e80a.png)

**Comment by jwalgran** [comment] 2015-05-18 14:23
This is by design. Only a map owner can see a dormant map, not all admins.

**Comment by kdeloach** [comment] 2015-05-18 14:28
I can still get to the management page if I access the URL directly even as a non-owner.

**Comment by jwalgran** [comment] 2015-05-18 14:34
Then that needs some investigation.

**Comment by kdeloach** [comment] 2015-05-18 22:25
Updated title and description.

**Comment by acouch** [comment] 2015-05-20 18:12
How do I make myself the "Map Owner"? Is there a table and column in the database for that?

**Comment by jwalgran** [comment] 2015-05-20 18:40
This issue involves code that is not in this repo. Closing.

**Closed by jwalgran** 2015-05-20 18:40 UTC
Labels: unverified

**Comment by acouch** [comment] 2015-05-21 14:54
@jwalgran I am logged with a user who both "staff" and "superuser" in the tree_map user database. I am not able to see the "Management page". I was referred to this ticket in the email group. Should I open a separate issue?

**Comment by acouch** [comment] 2015-05-21 14:59
@jwalgran Nevermind, a separate reply in the email group indicated that the management page is not yet available for the open source version. Is there a ticket tracking that effort?

**Comment by jwalgran** [comment] 2015-05-21 16:05
We will likely open several issues as we work through a redesign of our management pages.
