### ISSUE TITLE
Uncaught JavaScript exception 

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/OTM2#2019] opened 2015-05-28 20:40 UTC
Open the chrome developer tools and load https://www.opentreemap.org/treeocodeniagara/map/ -- we get:

```
Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of '__/treeocodeniagara/species/__data' exceeded the quota.
```

We should at least catch the exception so it doesn't prevent other code from executing.

**Comment by maurizi** [comment] 2015-05-28 20:46
This is a duplicate of https://github.com/OpenTreeMap/OTM2/issues/1857

**Closed by maurizi** 2015-05-28 20:46 UTC
Labels: unverified
